// layout.tsx
import type { Metadata } from "next";
import { Geist, Geist_Mono } from "next/font/google";
import "./globals.css";
import Navbar from "./components/Navbar";

const geistSans = Geist({
  variable: "--font-geist-sans",
  subsets: ["latin"],
});

const geistMono = Geist_Mono({
  variable: "--font-geist-mono",
  subsets: ["latin"],
});

export const metadata: Metadata = {
  title: "Finite Automata Designer",
<<<<<<< HEAD
  description: "Generated by create next app",
=======
  description: "Design and experiment with DFA and NFAs",
>>>>>>> b2257456505019e96ea1ba2e84e8e8b0f5028ea8
};

export default async function RootLayout({ children }: {
  children: React.ReactNode;
<<<<<<< HEAD
}) {
=======
}>) {
  // const session = 
  await getServerSession(authOptions);
>>>>>>> b2257456505019e96ea1ba2e84e8e8b0f5028ea8
  return (
    <html lang="en">
      <body className={`${geistSans.variable} ${geistMono.variable} antialiased`}>
        <Navbar />
        {children}
      </body>
    </html>
  );
}
